namespace UnityIsekaiGame.Quests
{
    public enum QuestCategory
    {
        Unknown,
        MainStory,
        SideQuest,
        GuildQuest,
        OrganizationQuest,
        GovernmentQuest,
        MerchantQuest,
        ProfessionQuest,
        PersonalQuest,
        SpecialAssignment,
        Bounty,
        Investigation,
        Delivery,
        Character,
        Exploration,
        Combat,
        Crafting,
        Social,
        Political,
        Legal,
        Travel,
        Discovery,
        Tutorial,
        Dynamic,
        WorldEvent,
        Custom
    }
}
